---
version: '3.5'
services:
  krest:
    image: confluentinc/cp-kafka-rest:${TAG}
    hostname: krest
    container_name: krest
    volumes:
      - "./krest:/etc/kafka-rest"
    ports:
      - 18082:18082
    environment:
      KAFKA_REST_LISTENERS: 'http://0.0.0.0:18082'
      KAFKA_REST_LOG4J_ROOT_LOGLEVEL: "INFO"
      KAFKA_REST_LOG4J_LOGGERS: "io.confluent.kafkarest.resources.v2=INFO"
      KAFKA_REST_BOOTSTRAP_SERVERS: ${KAFKA_SERVER}
      KAFKA_REST_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_REST_SASL_JAAS_CONFIG: |
            org.apache.kafka.common.security.plain.PlainLoginModule required \
            username="${KAFKA_API_KEY}" \
            password="${KAFKA_API_SECRET}";

      KAFKA_REST_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https
      KAFKA_REST_SASL_MECHANISM: PLAIN
      KAFKA_REST_CLIENT_BOOTSTRAP_SERVERS: ${KAFKA_SERVER}
      KAFKA_REST_CLIENT_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_REST_CLIENT_SASL_JAAS_CONFIG: |
            org.apache.kafka.common.security.plain.PlainLoginModule required \
            username="${KAFKA_API_KEY}" \
            password="${KAFKA_API_SECRET}";

      KAFKA_REST_CLIENT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https
      KAFKA_REST_CLIENT_SASL_MECHANISM: PLAIN
      # Confluent Cloud Schema Registry
      KAFKA_REST_SCHEMA_REGISTRY_URL: ${SR_SERVER}
      KAFKA_REST_CLIENT_BASIC_AUTH_CREDENTIALS_SOURCE: USER_INFO
      KAFKA_REST_CLIENT_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: ${SR_API_KEY}:${SR_API_SECRET}
      KAFKA_REST_CONFLUENT_REST_AUTH_PROPAGATE_METHOD: JETTY_AUTH
