scrape_configs:
  - job_name: Confluent Cloud
    scrape_interval: 30s
    scrape_timeout: 30s
    honor_timestamps: true
    static_configs:
      - targets:
        - api.telemetry.confluent.cloud
    scheme: https
    basic_auth:
      username: TXHMfake2EX4OV
      password: +Y7PcbeB6Io2fakeS8kwRy8AsYaWfs
    metrics_path: /v2/metrics/cloud/export
    params:
      "resource.kafka.id":
        - lkc-577702
        - lkc-jkz1m
      "resource.schema_registry.id":
        - lsrc-2vo02
